In [4]:
import tensorflow as tf
# import cifar10 

In [11]:
x = tf.placeholder("float64")
y = 2 * x

In [12]:
data = tf.random_uniform([4,5],10)

In [24]:
with tf.Session() as sess:
    x_data = sess.run(data)
    print(sess.run(y, feed_dict = {x:x_data}))

[[ 5.97019291  9.17050362  9.40855789  9.82953358 19.39525414]
 [11.21213722 18.72792816 10.00281525 17.03791237 19.96619987]
 [ 4.78915405  2.57295036  4.64905071  5.60094452  7.65714836]
 [ 2.99393845  3.72076797 12.21642685  3.95314407  5.29779339]]


In [25]:
sess = tf.InteractiveSession()

In [26]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])

In [27]:
I_matrix = tf.eye(5)
v_add = v_1 + v_2 #tf.add(v_1,v_2)

In [28]:
print(v_add.eval())

[3 3 8 7]


In [29]:
print(I_matrix.eval())

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
sess.close()

In [30]:
v_1 = tf.constant([1,2,3,4], name='v_1')
v_2 = tf.constant([2,1,5,3], name='v_2')
v_add = tf.add(v_1,v_2)

with tf.Session() as sess:
    writer = tf.summary.FileWriter('graphs', sess.graph)
    print(sess.run([v_1, v_2,v_add]))

writer.close()

[array([1, 2, 3, 4], dtype=int32), array([2, 1, 5, 3], dtype=int32), array([3, 3, 8, 7], dtype=int32)]


In [31]:
import tensorflow as tf

# Create two random matrices
a = tf.Variable(tf.random_normal([4,5], stddev=2))
b = tf.Variable(tf.random_normal([4,5], stddev=2))

#Element Wise Multiplication
A = a * b

#Multiplication with a scalar 2
B = tf.scalar_mul(2, A)

# Elementwise division, its result is
C = tf.div(a,b)

#Element Wise remainder of division
D = tf.mod(a,b)

In [32]:
# Pairwise cross product
#E = tf.cross(a,b)
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    writer = tf.summary.FileWriter('graphs', sess.graph)
    a,b,A_R, B_R, C_R, D_R = sess.run([a , b, A, B, C, D])
    print("a\n",a,"\nb\n",b, "a*b\n", A_R, "\n2*a*b\n", B_R, "\na/b\n", C_R, "\na%b\n", D_R)

a
 [[-0.34581965  2.0155222   1.583691   -3.5814202   4.0051746 ]
 [ 1.32602    -0.64756197 -0.8300725  -2.8089929  -1.7727053 ]
 [-1.8561641   0.25014314  2.884537   -0.7945547   1.08847   ]
 [-3.6213112  -0.58892465 -0.06799476 -2.1622994  -1.9002154 ]] 
b
 [[-0.7518117   1.786733    0.47469935 -1.8431079  -3.0981083 ]
 [ 0.7043651   2.107448    1.7289753   4.7195387  -0.314354  ]
 [ 0.5255439   3.581232    3.147119   -1.411378   -0.18946896]
 [-2.4869244  -1.9029957  -3.3996456   4.7437177  -1.3083881 ]] a*b
 [[  0.25999126   3.6012       0.7517771    6.600944   -12.408464  ]
 [  0.93400216  -1.3647033   -1.435175   -13.257151     0.557257  ]
 [ -0.97549576   0.8958206    9.077981     1.121417    -0.20623128]
 [  9.005927     1.1207211    0.23115808 -10.257338     2.4862192 ]] 
2*a*b
 [[  0.5199825    7.2024       1.5035542   13.201888   -24.816929  ]
 [  1.8680043   -2.7294066   -2.87035    -26.514301     1.114514  ]
 [ -1.9509915    1.7916412   18.155962     2.242834    -0.4124625

In [33]:
writer.close()

In [34]:
import tensorflow as tf

#Start an Interactive Session
sess = tf.InteractiveSession()

#Define a 5x5 Identity matrix
I_matrix = tf.zeros(5)
print(I_matrix.eval()) # This will print a zero matrix with 5 elements

#Define a Variable initialized to a 10x10 identity matrix
X = tf.Variable(tf.eye(10))
X.initializer.run()  # Initialize the Variable
print(X.eval()) # Evaluate the Variable and print the result

#Create a random 5x10 matrix
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()

#Multiply two matrices
product = tf.matmul(A, X)
print(product.eval())

#create a random matrix of 1s and 0s, size 5x10
b = tf.Variable(tf.random_uniform([5,10], 0, 2, dtype= tf.int32))
b.initializer.run()
print(b.eval())
b_new = tf.cast(b, dtype=tf.float32)

# Add the two matrices
t_sum = tf.add(product, b_new)
t_sub = product -b_new
print("A*X _b\n", t_sum.eval())
print("A*X - b\n", t_sub.eval())

[0. 0. 0. 0. 0.]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[-0.17668113  0.3418768   0.8439684   1.0421085   1.1907011   1.217085
   0.21459468 -0.23792838 -0.37712264 -0.15026723]
 [ 1.7582514   0.11594383 -0.19816738 -1.0890692  -0.84492165 -0.4463609
   0.25719205 -1.202865    1.3813652   1.2100058 ]
 [-0.07888043 -0.76614994 -0.5707574  -1.2302355   3.2975595   1.2245427
  -0.55585575  0.18740521  1.3929169  -1.7373625 ]
 [-1.5776305  -0.30428118 -1.0878478   0.4026691  -0.19044432 -0.90406615
   0.32933357  0.9011506  -0.56566256  0.29069605]
 [ 0.63956374 -1.1280127  -0.26106322  0.24408016  0.84324354 -0.43724787
   2.1963525   1.0599005   0.17558433  1.5126699 ]]
[[0 1 1 0 1 0 0 0 0 0]
 [0 1 0

In [40]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1819235665674310634
]


In [42]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'  ## To deactivate SSE Warnings
# Create a graph

# Selecting only CPU
with tf.device('/cpu:0'):
    rand_t = tf.random_uniform([50, 50], 0, 10, dtype=tf.float32, seed=0)
    a = tf.Variable(rand_t)
    b = tf.Variable(rand_t)
    c = tf.matmul(a, b)
    init = tf.global_variables_initializer()

In [43]:
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True,log_device_placement=True))

In [44]:
sess.run(init)

In [45]:
print(sess.run(c))

[[1405.2432  1441.7412  1364.38    ... 1480.2251  1279.0061  1620.0938 ]
 [1232.6588  1344.4459  1169.7092  ... 1205.1285  1040.5566  1421.9672 ]
 [1209.3167  1180.3208  1158.1396  ... 1200.0343  1014.03217 1222.5106 ]
 ...
 [1298.9648  1262.9236  1205.6917  ... 1396.479   1090.7252  1437.2411 ]
 [1118.2474  1209.0155  1077.7229  ... 1180.7023  1076.4692  1139.7421 ]
 [1200.8864  1297.2268  1260.0101  ... 1289.4296  1165.2449  1433.4185 ]]


In [46]:
sess.close()