In [1]:
import tensorflow as tf
# import cifar10 

/home/harshit/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/harshit/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/harshit/miniconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/harshit/miniconda3/env

In [ ]:
x = tf.placeholder("float64")
y = 2 * x

In [ ]:
data = tf.random_uniform([4,5],10)

In [18]:
with tf.Session() as sess:
    x_data = sess.run(data)
    print(sess.run(y, feed_dict = {x:x_data}))

NameError: name 'data' is not defined

In [20]:
sess = tf.InteractiveSession()

In [21]:
v_1 = tf.constant([1,2,3,4])
v_2 = tf.constant([2,1,5,3])

In [28]:
I_matrix = tf.Variable(tf.eye(20000))
I_matrix.initializer.run()
v_add = v_1 + v_2 #tf.add(v_1,v_2)

In [23]:
print(v_add.eval())

[3 3 8 7]


In [29]:
%time
print(I_matrix.eval())

CPU times: user 3 µs, sys: 4 µs, total: 7 µs
Wall time: 13.6 µs
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [30]:
sess.close()

In [ ]:
v_1 = tf.constant([1,2,3,4], name='v_1')
v_2 = tf.constant([2,1,5,3], name='v_2')
v_add = tf.add(v_1,v_2)

with tf.Session() as sess:
    writer = tf.summary.FileWriter('graphs', sess.graph)
    print(sess.run([v_1, v_2,v_add]))

writer.close()

In [ ]:
import tensorflow as tf

# Create two random matrices
a = tf.Variable(tf.random_normal([4,5], stddev=2))
b = tf.Variable(tf.random_normal([4,5], stddev=2))

#Element Wise Multiplication
A = a * b

#Multiplication with a scalar 2
B = tf.scalar_mul(2, A)

# Elementwise division, its result is
C = tf.div(a,b)

#Element Wise remainder of division
D = tf.mod(a,b)

In [ ]:
# Pairwise cross product
#E = tf.cross(a,b)
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    writer = tf.summary.FileWriter('graphs', sess.graph)
    a,b,A_R, B_R, C_R, D_R = sess.run([a , b, A, B, C, D])
    print("a\n",a,"\nb\n",b, "a*b\n", A_R, "\n2*a*b\n", B_R, "\na/b\n", C_R, "\na%b\n", D_R)

In [ ]:
writer.close()

In [ ]:
import tensorflow as tf

#Start an Interactive Session
sess = tf.InteractiveSession()

#Define a 5x5 Identity matrix
I_matrix = tf.zeros(5)
print(I_matrix.eval()) # This will print a zero matrix with 5 elements

#Define a Variable initialized to a 10x10 identity matrix
X = tf.Variable(tf.eye(10))
X.initializer.run()  # Initialize the Variable
print(X.eval()) # Evaluate the Variable and print the result

#Create a random 5x10 matrix
A = tf.Variable(tf.random_normal([5,10]))
A.initializer.run()

#Multiply two matrices
product = tf.matmul(A, X)
print(product.eval())

#create a random matrix of 1s and 0s, size 5x10
b = tf.Variable(tf.random_uniform([5,10], 0, 2, dtype= tf.int32))
b.initializer.run()
print(b.eval())
b_new = tf.cast(b, dtype=tf.float32)

# Add the two matrices
t_sum = tf.add(product, b_new)
t_sub = product -b_new
print("A*X _b\n", t_sum.eval())
print("A*X - b\n", t_sub.eval())

In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

In [31]:
import tensorflow as tf
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'  ## To deactivate SSE Warnings
# Create a graph

# Selecting only CPU
with tf.device('/cpu:0'):
    rand_t = tf.random_uniform([50, 50], 0, 10, dtype=tf.float32, seed=0)
    a = tf.Variable(rand_t)
    b = tf.Variable(rand_t)
    c = tf.matmul(a, b)
    init = tf.global_variables_initializer()

In [ ]:
sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True,log_device_placement=True))

In [ ]:
sess.run(init)

In [ ]:
print(sess.run(c))

In [ ]:
sess.close()